spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/marketmenu
spring.datasource.username=marketmenu_user
spring.datasource.password=marketmenu_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration